# Generated by Django 3.2.6 on 2021-08-13 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210813_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
